# =============================================================================
# Cloud SQL - PostgreSQL 16 production instance (Gap 3 / Gap 4)
# =============================================================================
#
# Managed PostgreSQL with:
#   * PostgreSQL 16 (matches docs/CLOUD_SETUP_CHECKLIST.md and migrations)
#   * REGIONAL availability (synchronous standby, automatic failover)
#   * Point-in-time recovery (PITR) enabled for binary log / WAL retention
#   * Private IP only (no public exposure) over the VPC private services access
#   * Application password sourced from Secret Manager (passed from root module)
#
# The password plaintext is generated by the root module (random_password) and
# stored as a Secret Manager version; it is never committed or logged.
# =============================================================================

# Cloud SQL instance with private IP, REGIONAL HA and PITR.
resource "google_sql_database_instance" "primary" {
  project             = var.project_id
  name                = var.instance_name
  region              = var.region
  database_version    = var.pg_version
  deletion_protection = true

  settings {
    tier              = var.db_tier
    availability_type = var.availability_type
    disk_size         = var.disk_size_gb
    disk_type         = "PD_SSD"

    # Private IP only. Requires the VPC private services access connection
    # (provisioned by the vpc module) to exist before apply.
    ip_configuration {
      ipv4_enabled       = false
      private_network    = var.network
      require_ssl        = true
    }

    # Point-in-time recovery and automated backups.
    backup_configuration {
      enabled                        = true
      point_in_time_recovery_enabled = true
      start_time                     = "02:00"
      location                       = var.region
      backup_retention_settings {
        retained_backups = 14
        retention_unit   = "COUNT"
      }
    }

    # Database flags aligned with the WorkBuddy RLS and audit requirements.
    database_flags {
      name  = "log_connections"
      value = "on"
    }
    database_flags {
      name  = "log_disconnections"
      value = "on"
    }
    database_flags {
      name  = "cloudsql.iam_authentication"
      value = "on"
    }

    insights_config {
      query_insights_enabled = true
    }

    labels = var.labels
  }

  lifecycle {
    prevent_destroy = true
  }

  depends_on = [var.network]
}

# Application database inside the instance.
resource "google_sql_database" "app" {
  project  = var.project_id
  name     = var.db_name
  instance = google_sql_database_instance.primary.name
  charset  = "UTF8"
  collation = "en_US.UTF8"
}

# Application database user. The password comes from the root module
# (random_password stored in Secret Manager) so no static credential is checked in.
resource "google_sql_user" "app" {
  project  = var.project_id
  name     = var.db_user
  instance = google_sql_database_instance.primary.name
  password = var.db_password
}
