from __future__ import annotations
from typing import Protocol

class MailConnector(Protocol):
    def authorization_url(self, tenant_id: str, user_id: str) -> str: ...
    def exchange_code(self, code: str) -> dict: ...
    def normalize_message(self, raw: dict) -> dict: ...
